### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by lovethakker02** [joaoferreira/SPFx-Google-Analytics#5]
@joaoferreira - I have cloned this repository and then run below commands as suggested in guideline:
git clone the repo
npm i
npm i -g gulp
gulp

I am getting below error in gulp, gulp clean, gulp build, gulp serve.

> Build target: DEBUG
> C:\Projects\SPFx-Google-Analytics-master\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:178
>             throw new Error(prefix + os.EOL +
>             ^
> 
> Error: JSON validation failed:
> C:\Projects\SPFx-Google-Analytics-master\config\tslint.json
> 
> Error: #/ (Defines configuration options for the...)
>        Additional properties not allowed: lintConfig,useDefaultConfigAsBase,removeExistingRules,displayAsWarning
>     at validateObjectWithCallback (C:\Projects\SPFx-Google-Analytics-master\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:178:19)
>     at JsonSchema.validateObjectWithCallback (C:\Projects\SPFx-Google-Analytics-master\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:193:13)
>     at JsonSchema.validateObject (C:\Projects\SPFx-Google-Analytics-master\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:175:14)
>     at TslintCmdTask._readConfigFile (C:\Projects\SPFx-Google-Analytics-master\node_modules\@microsoft\gulp-core-build\lib\tasks\GulpTask.js:311:28)
>     at TslintCmdTask.onRegister (C:\Projects\SPFx-Google-Analytics-master\node_modules\@microsoft\gulp-core-build\lib\tasks\GulpTask.js:87:32)
>     at Object.initialize (C:\Projects\SPFx-Google-Analytics-master\node_modules\@microsoft\gulp-core-build\lib\index.js:299:24)
>     at SPWebBuildRig.initialize (C:\Projects\SPFx-Google-Analytics-master\node_modules\@microsoft\sp-build-common\lib\BuildRig.js:61:19)
>     at SPWebBuildRig.initialize (C:\Projects\SPFx-Google-Analytics-master\node_modules\@microsoft\sp-build-common\lib\SPBuildRig.js:29:15)
>     at SPWebBuildRig.initialize (C:\Projects\SPFx-Google-Analytics-master\node_modules\@microsoft\sp-build-web\lib\SPWebBuildRig.js:15:15)
>     at Object.exports.initialize (C:\Projects\SPFx-Google-Analytics-master\node_modules\@microsoft\sp-build-web\lib\index.js:23:17)
> 

below are my vm configuration:

- gulp version
CLI version 2.1.0
Local version 3.9.1

- npm version
6.8.0

- node version 
v8.12.0

**Comment by lovethakker02** [comment]
Found the solution, DELETE tslint.json from config folder If you are getting error while building Gulp.
